apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: project-dance-templates
  description: A collection of RHDH templates for Project Dance
spec:
  type: url
  targets:
     - https://gitlab-gitlab.apps.cluster-jdqzf.sandbox2353.opentlc.com/rhdh/rh1-software-templates/blob/main/scaffolder-templates/quarkus-stssc-template/template.yaml
     - https://gitlab-gitlab.apps.cluster-jdqzf.sandbox2353.opentlc.com/rhdh/rh1-software-templates/blob/main/scaffolder-templates/register-component/template.yaml

